spring:
  datasource:
    url: jdbc:mysql://db-mysql:3306/bookappdb?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8084
