version: "3"
services:
  db-mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: bookappdb
      MYSQL_HOST: localhost

  db-mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_DATABASE: BookAppDB
      MONGO_PORT: 27017
      MONGO_HOST: localhost

  user-auth-service:
    image: user-auth-service
    build:
      context: book-app-services/UserAuthenticationService/
    depends_on:
      - db-mysql
    ports:
      - "8084:8084"

  favourite-service:
    image: favourite-service
    build:
      context: book-app-services/FavouriteService/
    depends_on:
      - db-mongo
    ports:
      - "8082:8082"

  recommendation-service:
    image: recommendation-service
    build:
      context: book-app-services/RecommendationService/
    depends_on:
      - db-mongo
    ports:
      - "8083:8083"

  user-service:
    image: user-service
    build:
      context: book-app-services/UserService/
    depends_on:
      - db-mongo
    ports:
      - "8081:8081"
