version: "3"
services:
  db-mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: bookappdb
      MYSQL_HOST: localhost
    restart: always

  db-mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_DATABASE: BookAppDB
      MONGO_PORT: 27017
      MONGO_HOST: localhost
    restart: always

  user-auth-service:
    image: user-auth-service
    build:
      context: book-app-services/UserAuthenticationService/
    depends_on:
      - db-mysql
    ports:
      - "8084:8084"
    restart: always

  favourite-service:
    image: favourite-service
    build:
      context: book-app-services/FavouriteService/
    depends_on:
      - db-mongo
    ports:
      - "8082:8082"
    restart: always

  recommendation-service:
    image: recommendation-service
    build:
      context: book-app-services/RecommendationService/
    depends_on:
      - db-mongo
    ports:
      - "8083:8083"
    restart: always

  book-app:
    image: app
    build:
      context: book-app/
    ports:
      - "7070:80"
