FROM java:8-jre
COPY ./target/UserAuthenticationService-0.0.1-SNAPSHOT.jar /usr/src/UserAuthenticationService-0.0.1-SNAPSHOT.jar
WORKDIR /usr/src
CMD ["java","-jar","/usr/src/UserAuthenticationService-0.0.1-SNAPSHOT.jar"]
